app = "eternal-garden-d46dd390-7a72-4a62-b5fa-fff04d289fe0"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1